proxy_location: EveryNode

http_options:
  host: 127.0.0.1
  port: 8901

grpc_options:
  port: 9000
  grpc_servicer_functions: []

applications:

- name: app1
  route_prefix: /
  import_path: resnet_pytorch:image_model
  runtime_env: {}
  deployments:
  - name: ImageModel
    num_replicas: 1
    ray_actor_options:
      num_cpus: 4
      num_gpus: 1